apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: secret
  
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: postgres
  DB_NAME: postgres
  DB_PASSWORD: secret
  DB_TIMEOUT: 10